var reqData = JSON.stringify({input:{
    address: {
            addressLine1: addressLine1v,
            addressLine10: addressLine10v,
            addressLine2: addressLine2v,
            addressLine3: addressLine3v,
            addressLine4: addressLine4v,
            addressLine5: addressLine5v,
            addressLine6: addressLine6v,
            addressLine7: addressLine7v,
            addressLine8: addressLine8v,
            addressLine9: addressLine9v,
            building: buildingv,
            cebucoCode: cebucoCodev,
            census: censusv,
            codes: {
              adaptation: address_adaptationv,
              detailCode: address_detailCodev,
              detail_list: address_detail_listv,
              options: address_optionsv,
              reliability: address_reliabilityv
            },
            congressionalDistrict: congressionalDistrictv,
            countryCode: countryCodev,
            countryISO3: countryISO3v,
            countryName: countryNamev,
            countryNumber: countryNumberv,
            county: countyv,
            countyCode: countyCodev,
            department: departmentv,
            district: districtv,
            dpvCoded: dpvCodedv,
            dpvFootnotes: dpvFootnotesv,
            dpvIndicator: dpvIndicatorv,
            dpvIsCMRA: dpvIsCMRAv,
            dpvIsNoStat: dpvIsNoStatv,
            dpvIsPBSA: dpvIsPBSAv,
            dpvIsVacant: dpvIsVacantv,
            eggCode: eggCodev,
            formalCountryName: formalCountryNamev,
            hausCode: hausCodev,
            houseNumber: houseNumberv,
            houseNumberAddition: houseNumberAdditionv,
            lacsIndicator: lacsIndicatorv,
            latitude: latitudev,
            locality: localityv,
            longitude: longitudev,
            lotNumber: lotNumberv,
            municipalityCode: municipalityCodev,
            name: namev,
            organization: organizationv,
            postBox: postBoxv,
            postIndicator: postIndicatorv,
            postTown: postTownv,
            postalCode: postalCodev,
            preIndicator: preIndicatorv,
            premise: premisev,
            province: provincev,
            provinceCode: provinceCodev,
            subDistrict: subDistrictv,
            thoroughfare: thoroughfarev,
            timezone: timezonev,
            urbanArea: urbanAreav,
            urbanization: urbanizationv
          },
          email: {
            addressee: addresseev,
            codes: {
              adaptation: email_adaptationv,
              detailCode: email_detailCodev,
              detail_list: email_detail_listv,
              options: email_optionsv,
              reliability: email_reliabilityv
            },
            countryCode: countryCodev,
            display_name: display_namev,
            domain: domainv,
            full_email_address: full_email_addressv,
            top_level: top_levelv
          },
          identity: {
            businessid: businessidv,
            codes: {
              adaptation: identity_adaptationv,
              detailCode: identity_detailCodev,
              detail_list: identity_detail_listv,
              options: identity_optionsv,
              reliability: identity_reliabilityv
            },
            completename: completenamev,
            contact_type: contact_typev,
            countryCode: countryCodev,
            dob: dobv,
            formofaddress: formofaddressv,
            function: functionv,
            gender: genderv,
            givenfullname: givenfullnamev,
            givennameinitials: givennameinitialsv,
            indicator: indicatorv,
            name_qualified: name_qualifiedv,
            nationalid: nationalidv,
            nationality: nationalityv,
            organization_name: organization_namev,
            passport: passportv,
            qualification_int_first: qualification_int_firstv,
            qualification_int_second: qualification_int_secondv,
            qualification_suceeding: qualification_suceedingv,
            qualificationpreceding: qualificationprecedingv,
            surname_first: surname_firstv,
            surname_prefix_first: surname_prefix_firstv,
            surname_prefix_second: surname_prefix_secondv
          },
          phone: {
            area_code: area_codev,
            calling_code: calling_codev,
            calling_from: calling_fromv,
            codes: {
              adaptation: phone_adaptationv,
              detailCode: phone_detailCodev,
              detail_list: phone_detail_listv,
              options: phone_optionsv,
              reliability: phone_reliabilityv
            },
            countryCode: countryCodev,
            formatted_international: formatted_internationalv,
            international_prefix: international_prefixv,
            line_type: line_typev,
            name: namev,
            number: numberv,
            phone_number: phone_numberv,
            timezone: timezonev,
            trunk: trunkv
          },
    credentials: {
	username:usernamev,
	password:passwordv,
	tenant:tenantv
    }
}}, undefined, 2);
